### ISSUE TITLE
Card #3088 missing

### ISSUE THREAD

**Issue by w00kie** [madcowfred/padherder-issues#954] opened 2016-09-06 07:14 UTC
Admittedly it's also kinda broken on padx: http://www.puzzledragonx.com/en/monster.asp?n=3088

It should be an evolution of #1772 Valkyrie Rose.

**Comment by TheBaddest** [comment] 2016-09-09 00:50
In the same vein, #3090 also does not have a proper evolution path. It should be #2745's ultimate evolution .

**Comment by ryuujinzero** [comment] 2016-11-17 18:56
Duplicate of #966

**Closed as completed by ryuujinzero** 2016-11-17 18:56 UTC
