### ISSUE TITLE
'My Extras' Suggestion

### ISSUE THREAD

**Issue by Gannonball09** [madcowfred/padherder-issues#274] opened 2014-03-10 18:27 UTC
Is it possible to add a tab for all the extra stuff (for example: collab mobs being used as skill up material or extra mobs using for awakening but need to be evo'd first) in order to keep track of the evo materials needed for them instead of adding them all to My Monsters? 

For example,
Monster - Quantity
Kitty Flamie - 24
Kitty Bubblie - 32
Kitty Woodsie - 29
Kitty Shynee - 27
Kitty Baddie - 30

Even having a separate spot in the My Materials section as well

So for Amelit it would say this for the above scenario-
H: 0
M: 0
L: 0
E: 54

I know this is probably wicked complicated, just thought I'd ask! :)

**Comment by madcowfred** [comment] 2014-03-19 06:05
Mostly a dupe of GH-143.

**Closed as completed by madcowfred** 2014-03-19 06:05 UTC
