### ISSUE TITLE
Random issues with "My Food"

### ISSUE THREAD

**Issue by raspberrytealeaf** [madcowfred/padherder-issues#321] opened 2014-04-29 23:44 UTC
1) BAO Grundy appears twice by Hermes under "My Food". The first one links to Padx entry 1051, the second links to Padx entry 1926.

2) I have 3 Byakkos in my box, 1 evoed/low priority, 2 non-evoed/zero priority. When I try to fill in like 5 Phantom Chasers by my evolved Byakko, it refreshes the page but with 0 Phantom Chasers entered. If I fill out my # of Phantom Chasers by the baby Byakkos, then the # actually saves and even appears near my evoed Byakko.

**Comment by madcowfred** [comment] 2014-04-30 08:13
1. THIS COLLAB IS THE WORST THING. Apparently the JP game is getting it now, but they're using different monster IDs to the US (which used IDs that a JP only collab used) and it is a complete mess aagh. I'll look in to deleting the old fake ID ones (19xx) and fixing things.
2. What browser? How are you changing the text? If you edit one of the Phantom Chaser boxes, do the others change value too? From a quick look it seems like using the up/down arrows to change the value doesn't update linked boxes properly.

**Comment by raspberrytealeaf** [comment] 2014-04-30 08:25
Using Chrome 34.[many numbers go here]. For text, I just filled in a # since that's faster on PC. Using arrows or filling in a # on the two un-evoed Byakko's updates the # of Phantom Chasers for both them and the evoed Byakko. Using arrows or filling in a # on the evoed Byakko doesn't update the number of Chasers. FWIW, the same thing happens in Firefox 29.

**Comment by madcowfred** [comment] 2014-04-30 08:49
Ah, the fun kind of bug that I can't reproduce. Does anything show up in the JS console? Ctrl-Shift-J on Chrome, Ctrl-Shift-K on Firefox - might need to reload page afterwards.

**Comment by raspberrytealeaf** [comment] 2014-04-30 08:54
Haha what the shit - writing in the #s works on my phone of all devices. I probably have some dumb browser issue on my PC.

**Comment by madcowfred** [comment] 2014-04-30 12:49
I've pushed some slightly more robust JS to update the boxes, let me know if that helps.

**Comment by kuiperfrog** [comment] 2014-04-30 15:44
Tried to use food page, but it seems lately it won't update the numbers either when I type them or use the up/down values and hit Save Changes. Using the latest Chrome on PC...

**Comment by madcowfred** [comment] 2014-04-30 16:08
Apparently I broke some things while refactoring some code, should be fixed now.

**Comment by raspberrytealeaf** [comment] 2014-05-02 23:51
Yay it works now. (Should I leave this open for grundy?)

**Comment by madcowfred** [comment] 2014-05-03 21:41
Grundy/etc should be fixed now also.

**Closed as completed by madcowfred** 2014-05-03 21:41 UTC
Labels: bug, food
