### ISSUE TITLE
Suggestion: More statistics in "My Team" page

### ISSUE THREAD

**Issue by nevets1219** [madcowfred/padherder-issues#658] opened 2015-05-27 03:04 UTC
An improvement for the lazy!

For row enhance teams, it would be nice to see how many row enhance (of what type) that is in the team. Similarly a count of "Skill Boost" would be helpful (maybe with some sort of marker noting which skills is immediately available). Same goes for most of the awakening skills.

http://www.puzzledragonx.com/en/article.asp?aid=4

**Comment by madcowfred** [comment] 2016-01-02 05:27
Duplicate of #577, closing this (and working on the feature, honest).

**Closed as completed by madcowfred** 2016-01-02 05:27 UTC
Labels: duplicate
