### ISSUE TITLE
Team selection could use a +egg number display after monsters

### ISSUE THREAD

**Issue by andyzaft** [madcowfred/padherder-issues#512] opened 2014-11-30 17:19 UTC
If one tries to make a team with multiple monsters that are at the same level and have the same id, it will always select the first, thus it's not possible for the user to pick the one wiht +297 as lead and the one with less +eggs later in the team. Now I realize this can be done by lowering the level of one, and then raising it back up once the team is made, so there is a workaround, but still would be a nice to have.

**Comment by andyzaft** [comment] 2014-11-30 17:22
I guess this is somewhat related to the #402 issue, I missed it on first look of issues. Still, the +egg display next to the names would greatly improve the interface on the long run.

**Comment by madcowfred** [comment] 2014-12-04 12:37
Yar, pretty much a duplicate of #402 - I'm working on it now, honest.

**Closed as completed by madcowfred** 2014-12-04 12:37 UTC
Labels: duplicate
