### ISSUE TITLE
[Suggestion] Name change option

### ISSUE THREAD

**Issue by User2300** [madcowfred/padherder-issues#292] opened 2014-04-01 16:44 UTC
I would like to change my user-name (or at least the name that is displayed publically) to match my in-game user-name.  It would be wonderful if you could add an option to change your user-name/display name.

Thanks!

**Comment by madcowfred** [comment] 2014-04-02 05:56
Dupe of GH-216.

**Closed as completed by madcowfred** 2014-04-02 05:56 UTC
Labels: duplicate
