### ISSUE TITLE
Mistrain/Sagirinokami Leader Skill bugged

### ISSUE THREAD

**Issue by Meldarion** [madcowfred/padherder-issues#736] opened 2015-09-05 05:34 UTC
Dragon Soul, the Leader Skill for Storm Dragon, Mistrain (1353) and Phantom Thunder Dragon, Sagirinokami (1354), is displayed incorrectly in PADherder.
It's listed as having the same affect as Resolve, but it's actual affect is "Dragon type cards ATK x2, RCV x2." 
Strangely - even though it displays incorrectly - the multipliers appear to still be applied correctly in the Team Builder.

**Comment by Meldarion** [comment] 2015-09-05 05:37
Screenshot of how it appears in PADherder:
![screenshot 65](https://cloud.githubusercontent.com/assets/14135284/9697888/a25d610a-536e-11e5-8a01-f0848c081f95.png)

**Comment by madcowfred** [comment] 2015-09-09 23:36
Duplicate of #705.

**Closed as completed by madcowfred** 2015-09-09 23:36 UTC
Labels: duplicate
