### ISSUE TITLE
Multiple Evolutions - Materials

### ISSUE THREAD

**Issue by Gannonball09** [madcowfred/padherder-issues#56] opened 2013-09-18 17:43 UTC
Is it possible to add the materials for the future evolutions of certain monsters? For example, I have Berserk. PadHerder shows me what I need to evolve Berserk into Siegfried. However, I also would like to have listed what I need to evolve Siegfried as well as the ultimate evolution after that. This feature would help people like me that like to plan for things long term. Thanks!

**Comment by madcowfred** [comment] 2013-09-19 08:29
Dupe of GH-18.

**Closed as completed by madcowfred** 2013-09-19 08:29 UTC
