### ISSUE TITLE
Feature Request: "Done" priority doesn't work for Enhance & Evolve monsters

### ISSUE THREAD

**Issue by DreadPirateShawn** [madcowfred/padherder-issues#487] opened 2014-10-31 20:14 UTC
Standard monsters can be flagged as "Done" priority, even if not fully evolved, by setting the "Level" value <= "Target" value, and by setting the "Evo" to "-None-". (Note: Awakenings, skill level, and plus levels are not included in this calculation.)

However, this doesn't work for Enhance or Evolve monsters, eg:
- Manekimewdra (#681) ~ Enhance type
- Keeper of Rainbow (#321) ~ Evolve type

Both are set to "Max" (aka 1) in both "Level" and "Target", and have only the option "-None-" for "Evo", which should be sufficient to move to "Done" -- however, both continue to appear mixed in with the relevant priority section (in my case "Zero") rather than moving to "Done".

Keeper of Rainbow (especially) is a monster that I use and would like to track (and perhaps skill up from time to time), but since it has no relevant XP or evolutions, I'd like to avoid inclusion in the standard mix of "Zero" priority monsters.

(Currently filed as "Bug" since setting the level and evo for standard monsters moves to "Done" but doing the same for these monsters does not -- however, depending on the desired solution, I could easily see this as "Enhancement" instead of "Bug", for instance if the right answer might involve a new Priority section or some such.)

**Comment by madcowfred** [comment] 2014-11-01 04:08
The "Done" thing was changed to fix some counter-intuitive behaviour. Current criteria:
- Monster's max level is ≥ 10.
- Current level = max level OR current level ≥ target level.
- Monster is max evolution OR target evolution is None.

... so basically it's by design. I'm not sure why awakenings aren't included, they definitely should be (assuming the current/target evolution of the monster has some). Skill level I believe was by design since I couldn't skill up my stupid Horus at the time :p

Evolve type monsters can't be skilled up (AFAIK) so they are specifically exempt from the 'Done' process, I'm not actually sure about Enhance.

**Comment by mccool37** [comment] 2014-11-07 06:16
To clarify on enhance material, they all either can't be leveled up (ie. the metal dragon series), can but don't have an active skill (ie. Moltrda) or can be leveled up but have their own separate skill that is already at Max (ie. Snow-globe Dragons). In all cases though, none of them can be skilled.

**Comment by DreadPirateShawn** [comment] 2014-11-07 16:31
Fwiw...
- Some evolve type monsters _can_ be skilled up, eg Keeper of Rainbow has 6 skill-up levels ~ http://www.puzzledragonx.com/en/monster.asp?n=321
- Enhance materials make sense that they can't be skilled up, fair enough

That said, both monsters have a potential use-case for including on teams in the "My Teams" section, which requires them to be entered in the "My Monsters" section -- but currently the only way to do so is to leave the monsters forever in the zero-to-high priority mix, with no way to push them "out of sight" into the "Done" section. Might be nice to be able to do so, either automatically (eg skilling up Keeper of Rainbow or setting its target skill to 1) or via a manual override option.

Just a thought. Retitling this ticket from "Bug:" to "Feature Request:".

**Comment by mccool37** [comment] 2014-11-08 16:31
Keepers cannot be skilled up. While they have skills with levels, because they are Evo Material you cannot fuse anything into them meaning they can never gain a level in that skill.
http://puzzleanddragonsforum.com/showthread.php?tid=8274
The same goes for any other Evo material with a skill (Gunma collab evo materials etc.)

**Comment by DreadPirateShawn** [comment] 2014-11-09 00:01
Oh interesting! Yeah, and I see that I can't select them for fusion in the game either.

In that case, it seems even more straightforward that Evo and Enhance monsters should not be included with the Zero/Low/Med/High priority buckets of monsters in the "My Monsters" section. They still need to be entered in order to use in "My Teams", but it'd be nice to group them separately since priority doesn't apply to them -- perhaps a "N/A" priority option?

**Comment by madcowfred** [comment] 2014-11-29 13:47
Some more priority levels are needed, I'm going to close this one and link it to #490 so I remember.

**Closed as completed by madcowfred** 2014-11-29 13:47 UTC
Labels: enhancement
