### ISSUE TITLE
Suggestion: Add skill up monster list for each monster listed under My Monsters

### ISSUE THREAD

**Issue by Jakeywakey** [madcowfred/padherder-issues#220] opened 2014-02-13 20:14 UTC
It would probably take a lot of work but I think it would be really nice to see a skill up list of monsters for each one, maybe shorten up the notes length to make room for it. Could maybe even remove the notes section and do some type of hover over for optional notes instead to make room for more stats on each monster.

Regardless I think its awesome what you are doing with this site and really appreciate how you manage suggestions and bugs with this system. Very cool stuff! Thanks again for making this site

**Comment by madcowfred** [comment] 2014-02-14 03:23
Dupe of GH-199, oops.

**Closed as completed by madcowfred** 2014-02-14 03:23 UTC
Labels: duplicate
