### ISSUE TITLE
Request: Feeder Priority

### ISSUE THREAD

**Issue by ghost** [madcowfred/padherder-issues#143] opened 2014-01-01 14:10 UTC
I've always got a bunch of stuff in my box that needs leveling/evolving so that I can feed it to something else for skill-ups or awakenings, and it would be nice to see how many materials I need to evolve them. Currently, having ten "AB The Blues" in the middle of my list at whatever priority just clutters things up. Having a separate priority for feeders would be great.

In the same vein, it would be nice if the site could detect that I have ten of the exact same monster and allow me to fold them up into one entry that showed their combined evolution requirements.

**Comment by theinfra** [comment] 2014-01-17 01:20
I... think this is what the "Priority" column for each monster is for? Or are you using it for something else? Or am I the weird one?

**Comment by Corbalt** [comment] 2014-02-04 06:14
Well, you can't use Zero priority since you do want them to show up on the My Materials page. It's not too unreasonable to imagine he is using his other priorities for other purposes and can't dedicate one solely to feeders -- basically there are not enough priority options for some people.

**Comment by madcowfred** [comment] 2014-02-13 14:02
Messing with the priorities is a lot of work for very little gain, not really planning to do so right now. 

I can see the use of having a feeder list that you can add things to and track as an extra 'F' field in My Materials - I'd much prefer to do that as a separate tab somewhere.

**Comment by madcowfred** [comment] 2014-02-16 07:09
Having just updated my PADherder box with feed stuff I can actually see a use for some sort of Feed priority :scream: The issue is that the current priorities are 0-3 and changing those now will make a bit of a mess until every single person gets around to reloading the page. I guess I could make Feed=-1 and do some magic to make them actually sort above Zero.

**Comment by ghost** [comment] 2014-02-16 22:40
I'm not sure if it really needs to be a priority, necessarily. If you could set monsters as belonging to another monster (as food), with a drop-down or by dragging them onto each-other or whatever, and then based on that have them show up visually in a way that indicates their status (indented below whatever they're food for or something), then their priority could be left alone. That's probably more complicated than just adding another priority level, though.

**Comment by uruloki** [comment] 2014-02-20 20:45
As another POV: I use the HIGH priority for cards I am actively working on. The MEDIUM priority is my feeders (and I usually put a note in them as well), and LOW is the rest of the box with the exception of ZERO which is my trophy box. YMMV.

**Comment by SingedKitty** [comment] 2014-02-22 16:54
Trouble with a feed priority is you still have to enter the monsters and stare at them cluttering your box just to keep track of the mats needed to evolve them.  Wouldn't a separate tab be easier for you and faster for users?

**Comment by madcowfred** [comment] 2014-04-20 11:08
Closing in favour of GH-286 which will be implemented Soon(tm).

**Closed as completed by madcowfred** 2014-04-20 11:08 UTC
