### ISSUE TITLE
Multiple Evo Anticipation in Materials

### ISSUE THREAD

**Issue by frankabus** [madcowfred/padherder-issues#30] opened 2013-08-14 19:28 UTC
It doesn't seem like the My Materials section of the site considers monsters that have multiple evolution stages. For example, if I have a Mystic Flame Knight and am planning on evolving it twice, it'll only count the materials necessary for the first evo but not the second. This makes it difficult for me to manage my materials, which is, I assume, what the point of that section is about.

**Comment by madcowfred** [comment] 2013-08-19 03:11
Dupe of GH-18.

**Closed as completed by madcowfred** 2013-08-19 03:11 UTC
