### ISSUE TITLE
Materials page is counting food items from max skill monsters

### ISSUE THREAD

**Issue by danhurt** [madcowfred/padherder-issues#353] opened 2014-05-26 17:38 UTC
The materials page is currently counting items on the food page that are not showing up. To create the issue: 
1) Add a ton of skill up monsters to the food page (like Eco Penpen)
2) Spend a stupid amount of time max skilling something like Lakshmi without removing the items from the food page
3) The skill up mons disappear from the food page due to max skill, but they still show up as required on the materials page

![screen shot 2014-05-26 at 10 33 51 am](https://cloud.githubusercontent.com/assets/7704630/3084630/65594666-e4fc-11e3-8711-72bfcc3c895f.png)

Account with the username Mephology exhibits this issue.

**Comment by madcowfred** [comment] 2014-06-11 14:15
Mostly a dupe of GH-327, closing this one.

**Closed as completed by madcowfred** 2014-06-11 14:15 UTC
