### ISSUE TITLE
Ability to send team to PDX simulator?

### ISSUE THREAD

**Issue by mezmerie** [madcowfred/padherder-issues#111] opened 2013-12-02 00:48 UTC
First of all, thank you for adding "Magical Search" to the team building page! However, there used to be a button where you could send your team to the PDX simulator and find out what your total stats would be, but now I can't find it. Am I missing something?

**Comment by madcowfred** [comment] 2013-12-02 00:50
Dupe of #108

**Closed as completed by madcowfred** 2013-12-02 00:50 UTC
