### ISSUE TITLE
Feature Request: Bulk Editing

### ISSUE THREAD

**Issue by Llammissar** [madcowfred/padherder-issues#423] opened 2014-08-19 05:59 UTC
I'd like to be able to select a large group of monsters and apply edits to them en masse.  e.g. for changing priorities or deleting things.

**Comment by Nalgaeryn** [comment] 2014-09-10 17:16
I'd also like this.

Also, a button next to Delete which moves the monster from Monsters to Food.

**Comment by Gavran** [comment] 2014-09-18 08:13
Thirding this request. It'd be great to mess with priorities when say, skill-up opportunities come around and not only is my box full but I also need to gather evo mats to get some of the skills.

**Comment by madcowfred** [comment] 2014-09-18 08:34
The issue with this continues to be that I'm not sure how I want to implement it, or how much pain it will be to implement. My last idea was to have a button on the sub-nav (add/bulk/etc bar) which pops into BULK EDIT mode:
- show a subnav panel for bulk edit controls? Change priority, delete monsters, ??
- set all rows to 40-50% opacity so they're all faded
- replace the 'Evolution' column with a giant checkbox or button, click button to select
- set selected rows to 100% opacity
- do stuff when you push the controls

This may also require some API support for efficiency - sending 25 PATCH or DELETE requests would be awful on a high latency connection.

**Comment by uXs** [comment] 2014-09-18 13:57
How about a checkbox in the edit dialog that says 'save these properties for all duplicates'. That would solve my problem where I need to change the priority for my 50 pixies.

Or, you could add one 'bulk edit' button that shows an editing dialog with all entries blanked. Everything you then fill in would be applied to all your monsters in your currently filtered list. There should also be a way to blank entries. Checkbox 'erase this field' for textboxes, an 'erase this field' entry for comboboxes, stuff like that.

**Comment by madcowfred** [comment] 2016-01-09 09:20
Closing this as a duplicate of #44

**Closed as completed by madcowfred** 2016-01-09 09:20 UTC
Labels: duplicate
