### ISSUE TITLE
Add a 'count' field to monsters

### ISSUE THREAD

**Issue by uXs** [madcowfred/padherder-issues#282] opened 2014-03-18 07:42 UTC
Add a 'count' or 'amount' field to monsters.

Two uses (that may or may not be the same):

-For things like ogre teams I don't want to add all of them seperately, but I do want to keep track of how many I have. I now put that in the description but that seems stupid.

-Skillup monsters. When I have skillup mons that need evo materials, I need to know how many evo mats I need. Like, say, the evo monster for Isis needs a red keeper and 2 dragon flowers. If I want to get 25 of those evo monsters, I'll need 25 red keepers and 50 dragon flowers. It would be nice to see that somewhere.

**Comment by madcowfred** [comment] 2014-03-19 06:05
Mostly a dupe of GH-143.

**Closed as completed by madcowfred** 2014-03-19 06:05 UTC
Labels: duplicate
