### ISSUE TITLE
Timer in the corner are wrong

### ISSUE THREAD

**Issue by sickcat99** [madcowfred/padherder-issues#1020] opened 2017-05-10 20:32 UTC
TAMADRA Infestation! in 594h 58m 
It always shows something like this.

I believe my settings are all correct:
<img width="533" alt="screen shot 2017-05-10 at 21 32 14" src="https://cloud.githubusercontent.com/assets/7051547/25919964/36b1c16a-35c8-11e7-9dac-9aa23c739894.png">

**Comment by sickcat99** [comment] 2017-05-10 20:33
Not my friend ID. I edited it for this.

**Comment by Raijinili** [comment] 2017-05-10 20:35
Dupe of #986.

(removed extra comment)

**Comment by sickcat99** [comment] 2017-05-10 20:42
oh :P

**Comment by ryuujinzero** [comment] 2017-05-10 20:43
Closing.

**Closed as completed by ryuujinzero** 2017-05-10 20:43 UTC
