### ISSUE TITLE
reCaptcha V1 is Shutdown

### ISSUE THREAD

**Issue by ahtobin** [madcowfred/padherder-issues#1056] opened 2018-04-29 23:22 UTC
Hi, I've just tried to create a new account which requires me to complete a Captcha. However, it appears that the captcha used is no longer supported. Here's an image of what I get, which says to go to g.co/recaptcha/upgrade to probably get the new version of their captcha. (Sorry it's been quite a while since I used GitHub, so I'm not sure if I'll get notifications if you respond to this. I'll try to check back though if you need someone to test out any changes!)

-Angela

![padherder_captcha](https://user-images.githubusercontent.com/11222713/39411972-f787dfc0-4bc8-11e8-8bc7-77be4247008e.png)

**Comment by ryuujinzero** [comment] 2018-05-08 14:12
Duplicate of #1054

**Closed as completed by ryuujinzero** 2018-05-08 14:12 UTC
Labels: duplicate

**Comment by madcowfred** [comment] 2018-05-10 04:24
This should be fixed now :(

**Comment by ahtobin** [comment] 2018-05-10 06:00
It did! I was just able to make an account :) Thank you!
