### ISSUE TITLE
Suggestion: Multiple item actions

### ISSUE THREAD

**Issue by dlim87** [madcowfred/padherder-issues#854] opened 2016-01-06 22:43 UTC
It might be helpful to have a mode where you can use checkboxes to select multiple monsters at once, and then apply the same action (Setting priorities, deleting, etc) at the same time to all of them

**Comment by madcowfred** [comment] 2016-01-09 09:19
Yup, it's been on the list forever, one of the oldest issues :( Duplicate of #44

**Closed as completed by madcowfred** 2016-01-09 09:19 UTC
Labels: duplicate
