### ISSUE TITLE
Suggestion: multiple sort layers

### ISSUE THREAD

**Issue by OhNoBananas** [madcowfred/padherder-issues#385] opened 2014-06-29 19:45 UTC
I'd love to be able to have multiple sort layers.

Right now you can tell the default sort is Color, then alphabetical. but seeing as in game alphabetical is not an option, its hard to sync the two up.

So I was thinking to be able to sort with things like color->rarity->hp would be helpful.

**Comment by madcowfred** [comment] 2014-07-11 17:28
There's currently no way to sort by arbitrary things. Also this appears to be a dupe of #268.

**Closed as completed by madcowfred** 2014-07-11 17:28 UTC
Labels: duplicate
