### ISSUE TITLE
suggestion: hyper button

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#859] opened 2016-01-11 16:37 UTC
Perhaps alongside the edit/evolve/delete button, it would be nice to have a 'hyper' or '297' button. 

Or perhaps a set of buttons: max level, max awaken, max eggs. Something like the PDX team simulator has would be nice to have.

**Comment by madcowfred** [comment] 2016-04-02 01:23
Dupe of #403 which has now been added.

**Closed as completed** 2016-04-02 01:22 UTC
Labels: duplicate
