### ISSUE TITLE
Is there a way to change evolutions in padherder?

### ISSUE THREAD

**Issue by wpnewborn** [madcowfred/padherder-issues#278] opened 2014-03-14 18:42 UTC
I just got the evo mats for F/L Horus but can't see a way to change my F/F Horus to F/L w/o deleting (and therefore deleting my saved teams) and re-adding from scratch.

**Comment by madcowfred** [comment] 2014-03-16 11:54
Nope, it's on the list of things to do. Closing as duplicate of GH-263.

**Closed as completed by madcowfred** 2014-03-16 11:54 UTC
Labels: duplicate
