### ISSUE TITLE
reCAPTCHA v1 IS SHUTDOWN

### ISSUE THREAD

**Issue by MFOCD** [madcowfred/padherder-issues#1057] opened 2018-05-08 14:09 UTC
reCAPTCHA v1 IS SHUTDOWN, disabling account creation.  Visit [g.co/recaptcha/upgrade](g.co/recaptcha/upgrade) for more info.

**Comment by ryuujinzero** [comment] 2018-05-08 14:11
Duplicate of #1054

**Closed as completed by ryuujinzero** 2018-05-08 14:11 UTC
Labels: duplicate

**Comment by madcowfred** [comment] 2018-05-10 04:25
This should be fixed now :(
